In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt

import plotly.graph_objects as go
import plotly.express as px

from VirtualSAS_theory import VirtualSAS_theory

# Load Initial Data

In [135]:
df1 = pd.read_csv('figure2.csv') #actually has both subplots
phase_names = df1.columns[::2].values
column_index = pd.MultiIndex.from_arrays([
    np.repeat(phase_names, 2),  # Repeat each phase name twice
    ['X', 'Y'] * len(phase_names)  # Alternate X and Y
])
df1.columns = column_index
df1 = df1.iloc[1:].reset_index(drop=True)
df1

               phase1v2                               phase2v2  \
                      X                  Y                   X
0    0.7935975344542534  45.41419677142751  1.2745280791360578
1    0.9213485938684407  43.24795884129293  1.1462799338875769
2    0.9737911493867095   39.6738806248369  1.2941629695907686
3    0.8246653990977819  37.18310778063602   1.445277063216885
4    0.9553989735177417  35.66668530738546  1.8707825373746338
..                  ...                ...                 ...
172                 NaN                NaN   52.31008214343412
173                 NaN                NaN   51.50703997812821
174                 NaN                NaN  60.280107867626036
175                 NaN                NaN   60.93352719680872
176                 NaN                NaN   39.47184630106003

                                   phase3v2                      \
                      Y                   X                   Y
0     0.196939193975318   9.536343188059995  0.2399060507773143
1     2.254874547962558  10.089599721631924  0.7806733027625512
2     4.474890951795089  13.398948663460459    1.80507400365358
3      7.39887410058531  15.950241707986919   2.668046079856836
4     10.10587928270514  21.395817022704392   4.122767773925361
..                  ...                 ...                 ...
172  19.568280952913554                 NaN                 NaN
173  24.605469186891856                 NaN                 NaN
174   31.03763561122918                 NaN                 NaN
175   38.40137195690267                 NaN                 NaN
176   27.43764679566045                 NaN                 NaN

                    phase1                                     phase2  \
                         X                   Y                      X
0     -0.38152076341790986   43.42081955653599  -0.010095273344520983
1    -0.009586817788635571  42.968004997243355     2.0053347967863595
2       0.3641832040179711   42.81530308037906      4.049327726266215
3       0.7235130684405138   42.39507604132587      5.978737388884989
4       1.1294352284539477   41.89419108163888      8.013234890591995
..                     ...                 ...                    ...
172                    NaN                 NaN                    NaN
173                    NaN                 NaN                    NaN
174                    NaN                 NaN                    NaN
175                    NaN                 NaN                    NaN
176                    NaN                 NaN                    NaN

                                        phase3
                      Y                      X                     Y
0    11.022672886342022  -0.004734951214686589  -0.20720197566159015
1     8.696675962145918   0.013592245400652736    1.3973211152022529
2     6.531488701844843   0.041568021849695214    2.7880694544595883
3     4.418245515516212   0.031077105681304396     4.766538827238094
4     2.145979439335825   0.011141812427014397     6.530978194975333
..                  ...                    ...                   ...
172                 NaN                    NaN                   NaN
173                 NaN                    NaN                   NaN
174                 NaN                    NaN                   NaN
175                 NaN                    NaN                   NaN
176                 NaN                    NaN                   NaN

[177 rows x 12 columns]

build the multiindex and add in the extra column for the first slice (with 'v2' in the name)

In [4]:
# Get columns with 'v2' in their names for potential future use (currently not used)
v2_columns = [col for col in df1.columns if 'v2' in col[0]]

# Create a dictionary to hold our new multiindex columns data
new_data = {}

# Process each phase to build columns
for phase in ['phase1v2', 'phase2v2', 'phase3v2']:
    # Define the original X and Y column keys for the phase
    x_col = (phase, 'X')
    y_col = (phase, 'Y')
    
    # Add the renamed columns to our dictionary
    new_data[(phase, 'protein')] = df1[x_col]
    new_data[(phase, 'temperature')] = df1[y_col]
    new_data[(phase, 'glycerol')] = 0

# Create the new dataframe from the dictionary
new_df = pd.DataFrame(new_data)

# Convert the columns to a proper MultiIndex with descriptive names
new_df.columns = pd.MultiIndex.from_tuples(new_df.columns, names=['phase', 'measurement'])

# Display the new dataframe
new_df

phase                  phase1v2                              \
measurement             protein        temperature glycerol
0            0.7935975344542534  45.41419677142751        0
1            0.9213485938684407  43.24795884129293        0
2            0.9737911493867095   39.6738806248369        0
3            0.8246653990977819  37.18310778063602        0
4            0.9553989735177417  35.66668530738546        0
..                          ...                ...      ...
172                         NaN                NaN        0
173                         NaN                NaN        0
174                         NaN                NaN        0
175                         NaN                NaN        0
176                         NaN                NaN        0

phase                  phase2v2                               \
measurement             protein         temperature glycerol
0            1.2745280791360578   0.196939193975318        0
1            1.1462799338875769   2.254874547962558        0
2            1.2941629695907686   4.474890951795089        0
3             1.445277063216885    7.39887410058531        0
4            1.8707825373746338   10.10587928270514        0
..                          ...                 ...      ...
172           52.31008214343412  19.568280952913554        0
173           51.50703997812821  24.605469186891856        0
174          60.280107867626036   31.03763561122918        0
175           60.93352719680872   38.40137195690267        0
176           39.47184630106003   27.43764679566045        0

phase                  phase3v2
measurement             protein         temperature glycerol
0             9.536343188059995  0.2399060507773143        0
1            10.089599721631924  0.7806733027625512        0
2            13.398948663460459    1.80507400365358        0
3            15.950241707986919   2.668046079856836        0
4            21.395817022704392   4.122767773925361        0
..                          ...                 ...      ...
172                         NaN                 NaN        0
173                         NaN                 NaN        0
174                         NaN                 NaN        0
175                         NaN                 NaN        0
176                         NaN                 NaN        0

[177 rows x 9 columns]

do the same for the second slice

In [5]:
# Get columns without 'v2' in their names
not_v2_columns = [col for col in df1.columns if 'v2' not in col[0]]

# Create a dictionary to hold our new multiindex columns data
new_data_not_v2 = {}

# Process each phase to build columns
for phase in ['phase1', 'phase2', 'phase3']:
    # Define the original X and Y column keys for the phase
    x_col = (phase, 'X')
    y_col = (phase, 'Y')
    
    # Add the renamed columns to our dictionary
    new_data_not_v2[(phase, 'glycerol')] = df1[x_col]
    new_data_not_v2[(phase, 'temperature')] = df1[y_col]
    new_data_not_v2[(phase, 'protein')] = 50

# Create the new dataframe from the dictionary
new_df_not_v2 = pd.DataFrame(new_data_not_v2)

# Convert the columns to a proper MultiIndex with descriptive names
new_df_not_v2.columns = pd.MultiIndex.from_tuples(new_df_not_v2.columns, names=['phase', 'measurement'])

# Display the new dataframe
new_df_not_v2

phase                       phase1                              \
measurement               glycerol         temperature protein
0             -0.38152076341790986   43.42081955653599      50
1            -0.009586817788635571  42.968004997243355      50
2               0.3641832040179711   42.81530308037906      50
3               0.7235130684405138   42.39507604132587      50
4               1.1294352284539477   41.89419108163888      50
..                             ...                 ...     ...
172                            NaN                 NaN      50
173                            NaN                 NaN      50
174                            NaN                 NaN      50
175                            NaN                 NaN      50
176                            NaN                 NaN      50

phase                       phase2                              \
measurement               glycerol         temperature protein
0            -0.010095273344520983  11.022672886342022      50
1               2.0053347967863595   8.696675962145918      50
2                4.049327726266215   6.531488701844843      50
3                5.978737388884989   4.418245515516212      50
4                8.013234890591995   2.145979439335825      50
..                             ...                 ...     ...
172                            NaN                 NaN      50
173                            NaN                 NaN      50
174                            NaN                 NaN      50
175                            NaN                 NaN      50
176                            NaN                 NaN      50

phase                       phase3
measurement               glycerol           temperature protein
0            -0.004734951214686589  -0.20720197566159015      50
1             0.013592245400652736    1.3973211152022529      50
2             0.041568021849695214    2.7880694544595883      50
3             0.031077105681304396     4.766538827238094      50
4             0.011141812427014397     6.530978194975333      50
..                             ...                   ...     ...
172                            NaN                   NaN      50
173                            NaN                   NaN      50
174                            NaN                   NaN      50
175                            NaN                   NaN      50
176                            NaN                   NaN      50

[177 rows x 9 columns]

combine the common 'phases' from each slice into single dataframes

In [6]:
df_list = []
for phasename in ['phase1', 'phase2', 'phase3']:
    # Drop NaN values from 'phase1' and 'phase1v2' in new_df
    df1 = new_df[phasename+'v2'].dropna().astype(float)
    df2 = new_df_not_v2[phasename].dropna().astype(float)

    # Combine 'phase1' and 'phase1v2' in new_df_not_v2
    df12 = pd.concat([df1, df2], axis=0, ignore_index=True)
    display(df12)

    df_list.append(df12)

measurement    protein  temperature   glycerol
0             0.793598    45.414197   0.000000
1             0.921349    43.247959   0.000000
2             0.973791    39.673881   0.000000
3             0.824665    37.183108   0.000000
4             0.955399    35.666685   0.000000
..                 ...          ...        ...
255          50.000000    39.505000  10.467956
256          50.000000    41.537455  10.495626
257          50.000000    42.713408  10.456878
258          50.000000    43.673288  10.255943
259          50.000000    39.188996  10.830875

[260 rows x 3 columns]

measurement    protein  temperature   glycerol
0             1.274528     0.196939   0.000000
1             1.146280     2.254875   0.000000
2             1.294163     4.474891   0.000000
3             1.445277     7.398874   0.000000
4             1.870783    10.105879   0.000000
..                 ...          ...        ...
322          50.000000    35.267027   5.467592
323          50.000000    35.641229   5.457867
324          50.000000    29.715392  10.205326
325          50.000000    21.365542   9.636519
326          50.000000    29.865609   9.441531

[327 rows x 3 columns]

measurement    protein  temperature  glycerol
0             9.536343     0.239906  0.000000
1            10.089600     0.780673  0.000000
2            13.398949     1.805074  0.000000
3            15.950242     2.668046  0.000000
4            21.395817     4.122768  0.000000
..                 ...          ...       ...
243          50.000000     0.441780  0.539108
244          50.000000     3.116453  0.604657
245          50.000000     6.004007  0.593732
246          50.000000     8.303203  0.573542
247          50.000000    10.067387  0.534513

[248 rows x 3 columns]

In [134]:
import plotly.express as px
import plotly.graph_objects as go

# Create a 3D scatter plot for each dataframe in df_list
fig = go.Figure()

# Define colors for each phase
colors = ['red', 'green', 'blue']

for i, df in enumerate(df_list):
    fig.add_trace(go.Scatter3d(
        x=df['protein'],
        y=df['temperature'],
        z=df['glycerol'],
        mode='markers',
        marker=dict(size=5, color=colors[i], opacity=0.8),
        name=f'Phase {i+1}'
    ))

# Update layout for better visualization
fig.update_layout(
    scene=dict(
        xaxis_title='Protein Concentration',
        yaxis_title='Temperature',
        zaxis_title='Glycerol Concentration'
    ),
    title='3D Scatter Plot of Phases',
    margin=dict(l=0, r=0, b=0, t=50)
)

# Show the plot
fig.show()

finally, make master dataset

In [8]:
import xarray as xr

ds_list = []
for i, df in enumerate(df_list):


    ds = xr.Dataset()
    ds['composition'] = df.to_xarray().to_array('component')
    ds['labels'] = ('index',np.ones(ds.sizes['index'])*i)
    ds = ds.rename({'index': 'sample'})
    ds_list.append(ds)

ds = xr.concat(ds_list, dim='sample')
ds = ds.transpose('sample', 'component')

ds

<xarray.Dataset> Size: 33kB
Dimensions:      (component: 3, sample: 835)
Coordinates:
  * sample       (sample) int64 7kB 0 1 2 3 4 5 6 ... 242 243 244 245 246 247
  * component    (component) object 24B 'protein' 'temperature' 'glycerol'
Data variables:
    composition  (sample, component) float64 20kB 0.7936 45.41 ... 10.07 0.5345
    labels       (sample) float64 7kB 0.0 0.0 0.0 0.0 0.0 ... 2.0 2.0 2.0 2.0

In [136]:
ds.to_netcdf('250609_base_dataset.nc')
ds

<xarray.Dataset> Size: 33kB
Dimensions:      (component: 3, sample: 835)
Coordinates:
  * sample       (sample) int64 7kB 0 1 2 3 4 5 6 ... 242 243 244 245 246 247
  * component    (component) object 24B 'protein' 'temperature' 'glycerol'
Data variables:
    composition  (sample, component) float64 20kB 0.7936 45.41 ... 10.07 0.5345
    labels       (sample) float64 7kB 0.0 0.0 0.0 0.0 0.0 ... 2.0 2.0 2.0 2.0

# Extrapolate

Now we (extap/interp)polate over the entire composition space

In [12]:
from AFL.double_agent import *
from AFL.double_agent import load_prefab,list_prefabs

In [13]:
list_prefabs()

Available Prefabricated Pipelines:
|-----------------------|-------------------------------------------------------------------------------------------------------------|
| Name                  | Description                                                                                                 |
|-----------------------|-------------------------------------------------------------------------------------------------------------|
| find_boundaries       | A simlarity-clustering-classification pipeline for finding boundaries in measurement data                   |
| preprocess            | A pipeline that generates a Cartesian grid, normalizes data, and calculates derivatives using Savgol filter |
| similarity_clustering | A simlarity-clustering pipeline for clustering measurements into groups                                     |
|-----------------------|-------------------------------------------------------------------------------------------------------------|
Total: 3 prefabricated pipeline(s)

In [110]:
load_prefab('find_boundaries').print_code()

Pipeline code has been prepared in a new cell below.

In [13]:
with Pipeline(name = "find_boundaries") as p:

    CartesianGrid(
        output_variable="composition_grid",
        sample_dim="grid",
        grid_spec = {'protein':{'min': 0.0, 'max': 80.0, 'steps': 25},
                     'glycerol':{'min': 0.0, 'max': 12.0, 'steps': 25},
                     'temperature':{'min': 0.0, 'max': 50.0, 'steps': 25}}
    )

    Standardize(
        input_variable="composition",
        output_variable="normalized_composition",
        dim="sample",
        component_dim="component",
        scale_variable=None,
        min_val={'protein': 0.0, 'glycerol': 0.0, 'temperature': 0.0},
        max_val={'protein': 80.0, 'glycerol': 12.0, 'temperature': 50.0},
        name="Standardize",
    )

    Standardize(
        input_variable="composition_grid",
        output_variable="normalized_composition_grid",
        dim="grid",
        component_dim="component",
        scale_variable=None,
        min_val={'protein': 0.0, 'glycerol': 0.0, 'temperature': 0.0},
        max_val={'protein': 80.0, 'glycerol': 12.0, 'temperature': 50.0},
        name="Standardize",
    )

    GaussianProcessClassifier(
        feature_input_variable="normalized_composition",
        predictor_input_variable="labels",
        output_prefix="extrap",
        grid_variable="normalized_composition_grid",
        grid_dim="grid",
        sample_dim="sample",
        kernel="Matern",
        kernel_kwargs={'length_scale': 1.0, 'nu': 1.5},
        optimizer="fmin_l_bfgs_b",
        name="GaussianProcessClassifier",
    )

p.print()

PipelineOp                               input_variable ---> output_variable
----------                               -----------------------------------
0  ) <CartesianGridGenerator>            CartesianGridGenerator ---> composition_grid
1  ) <Standardize>                       composition ---> normalized_composition
2  ) <Standardize>                       composition_grid ---> normalized_composition_grid
3  ) <GaussianProcessClassifier>         ['normalized_composition', 'labels', 'normalized_composition_grid'] ---> ['extrap_mean', 'extrap_entropy']

Input Variables
---------------
0) CartesianGridGenerator
1) composition
2) labels

Output Variables
----------------
0) extrap_mean
1) extrap_entropy

In [14]:
ds1 = p.calculate(ds)
ds1

  0%|          | 0/4 [00:00<?, ?it/s]

<xarray.Dataset> Size: 1MB
Dimensions:                      (sample: 835, component: 3, grid: 15625)
Coordinates:
  * sample                       (sample) int64 7kB 0 1 2 3 ... 244 245 246 247
  * component                    (component) object 24B 'protein' ... 'glycerol'
Dimensions without coordinates: grid
Data variables:
    composition                  (sample, component) float64 20kB 0.7936 ... ...
    labels                       (sample) float64 7kB 0.0 0.0 0.0 ... 2.0 2.0
    composition_grid             (grid, component) float64 375kB 0.0 ... 12.0
    normalized_composition       (sample, component) float64 20kB 0.00992 ......
    normalized_composition_grid  (grid, component) float64 375kB 0.0 0.0 ... 1.0
    extrap_mean                  (grid) int64 125kB 1 1 1 1 1 0 ... 0 0 0 0 0 0
    extrap_entropy               (grid) float64 125kB 1.034 1.002 ... 1.006 1.01
    extrap_y_prob                (grid) float64 125kB 1.034 1.002 ... 1.006 1.01

In [128]:
plot_scatter_plotly(
    dataset=ds1.isel(grid=slice(None,None,None)),
    component_variable='composition_grid',
    labels='extrap_mean',
    discrete_labels=True,
)

In [64]:
boundary_dataset = ds1.isel(grid=slice(None,None,None)).copy()
boundary_dataset = boundary_dataset[['composition_grid','extrap_mean']]
boundary_dataset = boundary_dataset.rename({'extrap_mean':'labels','composition_grid':'composition','grid':'sample'})
boundary_dataset.attrs['labels'] = 'labels'
boundary_dataset.attrs['components'] = 'composition'
boundary_dataset.to_netcdf('250609-extrap_dataset.nc')

# Expand Dataset 

One last step, we need an 'expanded' version of each phase. This is so that compositions near the boundaries still work. We'll expand each part of the grid around its center of mass

In [129]:
# Set expansion percentage (e.g., 10% expansion)
expansion_percentage = 0.1
boundary_dataset2 = boundary_dataset.copy()

# Group by labels and expand positions
expanded_compositions = []
expanded_labels= []
for label, sds in boundary_dataset2.groupby('labels'):
    composition = sds['composition']
    center = composition.mean('sample')
    vectors_from_center = composition - center
    # Expand each point radially from the center by the expansion percentage
    expanded_composition = center + (1 + expansion_percentage) * vectors_from_center
    expanded_compositions.append(expanded_composition)
    expanded_labels.append(sds.labels)

expanded_composition = xr.concat(expanded_compositions,dim='sample')
expanded_labels = xr.concat(expanded_labels,dim='sample')

boundary_dataset2['composition'] = expanded_composition
boundary_dataset2['labels'] = expanded_labels
boundary_dataset2

<xarray.Dataset> Size: 500kB
Dimensions:      (component: 3, sample: 15625)
Coordinates:
  * component    (component) object 24B 'protein' 'temperature' 'glycerol'
Dimensions without coordinates: sample
Data variables:
    composition  (component, sample) float64 375kB -3.507 -3.507 ... 9.008 9.558
    labels       (sample) int64 125kB 0 0 0 0 0 0 0 0 0 0 ... 2 2 2 2 2 2 2 2 2
Attributes:
    labels:      labels
    components:  composition

In [130]:
plot_scatter_plotly(
    dataset=boundary_dataset2,
    component_variable='composition',
    labels='labels',
    discrete_labels=True,
)

In [133]:
boundary_dataset2.to_netcdf('250610-extrap_expand_dataset.nc')

# Check Virtual Instrument

In [131]:
reference_data_path = './SANS/'
inst_client = VirtualSAS_theory()
inst_client.boundary_dataset = boundary_dataset2
inst_client.trace_boundaries(hull_tracing_ratio=0.25)

for fname in ['low_q.ABS', 'med_q.ABS', 'high_q.ABS']:
    data = pd.read_csv(str(pathlib.Path(reference_data_path) / fname),sep=r'\s+')#, delim_whitespace=True)
    inst_client.add_configuration(
        q=list(data.q),
        I=list(data.I),
        dI=list(data.dI),
        dq=list(data.dq),
        reset=False
    )

inst_client.add_sasview_model(
    label='2',
    model_name='polymer_excl_volume',
    model_kw={
        'scale': 1.0,
        'background': 1.0,
        'rg': 100.0,
    }
)

inst_client.add_sasview_model(
    label='1',
    model_name='sphere',
    model_kw={
        'scale': 0.005,
        'background': 1.0,
        'sld': 1.0,
        'sld_solvent': 6.0,
        'radius': 10,
    }
)

inst_client.add_sasview_model(
    label='0',
    model_name='power_law',
    model_kw={
        'scale': 1e-7,
        'background': 1.0,
        'power': 4.0,
    }
)
inst_client

In [132]:
# Create a 3D scatter plot with plotly
fig = go.Figure()

# Add points for each phase with different colors
colors = ['red', 'blue', 'green']
phase_names = ['Phase 0', 'Phase 1', 'Phase 2']

# Add hull meshes if they exist
for i, hull in enumerate(inst_client.hulls.values()):
    if hasattr(hull, 'vertices') and hasattr(hull, 'faces'):
        vertices = hull.vertices
        faces = hull.faces
        
        fig.add_trace(go.Mesh3d(
            x=vertices[:, 0],
            y=vertices[:, 1], 
            z=vertices[:, 2],
            i=faces[:, 0],
            j=faces[:, 1],
            k=faces[:, 2],
            color=colors[i],
            opacity=0.3,
            name=f'{phase_names[i]} Hull',
            showlegend=True
        ))
# Add cube wireframe from (0,0,0) to (80,40,12)
cube_vertices = [
    [0, 0, 0], [80, 0, 0], [80, 50, 0], [0, 50, 0],  # bottom face
    [0, 0, 12], [80, 0, 12], [80, 50, 12], [0, 50, 12]  # top face
]

# Define the edges of the cube
cube_edges = [
    # Bottom face edges
    [0, 1], [1, 2], [2, 3], [3, 0],
    # Top face edges  
    [4, 5], [5, 6], [6, 7], [7, 4],
    # Vertical edges
    [0, 4], [1, 5], [2, 6], [3, 7]
]

# Add each edge as a line
for edge in cube_edges:
    p1, p2 = cube_vertices[edge[0]], cube_vertices[edge[1]]
    fig.add_trace(go.Scatter3d(
        x=[p1[0], p2[0]],
        y=[p1[1], p2[1]],
        z=[p1[2], p2[2]],
        mode='lines',
        line=dict(color='black', width=4),
        showlegend=False
    ))

fig.update_layout(
    title='3D Phase Diagram with Concave Hulls',
    scene=dict(
        xaxis_title='Protein Concentration',
        yaxis_title='Temperature',
        zaxis_title='Glycerol Concentration',
        camera=dict(
            eye=dict(x=1.5, y=1.5, z=1.5)
        )
    ),
    width=1000,
    height=800
)

fig.show()